# Generated by Django 5.2.5 on 2025-11-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tbl_employee",
        ),
    ]
