# Generated by Django 5.2.5 on 2025-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0002_delete_tbl_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=200)),
                ("employee_email", models.EmailField(max_length=254)),
                ("employee_phone", models.CharField(max_length=15)),
                ("employee_designation", models.CharField(max_length=150)),
                ("employee_department", models.CharField(max_length=150)),
                ("employee_join_date", models.DateField()),
            ],
        ),
    ]
