# Generated by Django 5.2.5 on 2025-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_employee",
            name="employee_password",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
